"""Remove references to Course and update product model

Revision ID: 98581cfdbf05
Revises: 3988b6f5a0a2
Create Date: 2025-05-09 22:34:11.298380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98581cfdbf05'
down_revision = '3988b6f5a0a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('course_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('duration', sa.VARCHAR(length=50), nullable=False),
    sa.Column('video_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
